### ISSUE TITLE
Unable to select more than 10 sections

### ISSUE THREAD

**Issue by simonnoff** [LeonardoCardoso/SectionedSlider#12]
When I try to have more than 10 sections (for example 20) and try to select 16 (selectedSection: 16, sections: 20) on slider initialization, I was not able to see the 16 selected sections. After looking at the code, I realized that because on initialization, the _selectedSection_ variable is updated before the _sections_ variable, my change on _sections_ value does not take place and thus _selectedSection_ is capped to 10.

Solution: if you swap the place of initializing _sections_ and _selectedSection_, everything should work. For reference, swap line 490 with line 491. The problem comes from didSet on line 440. 

I don't mind forking the repo and using my own version of the slider, but I really want to benefit from future updates since this is one great project which is made amazingly well. Congratulations :) I would be thankful if you made this simple fix.

**Comment by leonardocardoso** [comment]
Hi, @simonnoff. Can you create a PR with the fix?

**Comment by simonnoff** [comment]
@LeonardoCardoso  Yes, I will do so.

**Comment by simonnoff** [comment]
Just did it, waiting for approval!

**Comment by leonardocardoso** [comment]
@simonnoff done. Thank you!
