### ISSUE TITLE
0.0.2 unable to find in cocoa pods

### ISSUE THREAD

**Issue by CarlosLabrado** [LeonardoCardoso/SectionedSlider#2]
Hello, there's an error with cocoa pods:

  pod 'SectionedSlider', '~> 0.0.2'

[!] Unable to find a specification for `SectionedSlider (~> 0.0.2)`

**Comment by leonardocardoso** [comment]
Have you tried to do a `pod update`?

**Comment by CarlosLabrado** [comment]
This did it, thanks! sorry for wasting your time :(
