### ISSUE TITLE
Can't install CocoaPod

### ISSUE THREAD

**Issue by sdevo619** [LeonardoCardoso/SectionedSlider#3]
Im not sure whats happing but, I use Cocoa Pods quite frequently so I know it's not a noob issue, but I can't get the CocoaPod to install, but as soon as I remove SectionedSlider, it works fine. Any ideas? Running Xcode 8.3.3 and updated my CocoaPod installation too.

**Comment by leonardocardoso** [comment]
I will check it out, @sdevo619.

Have you tried cleaning your build folder or delete derived data?

**Comment by sdevo619** [comment]
No I haven't tried that yet, but I will. Since I wasn't able to get the CocoaPod to work, I imported the file manually and got it working that way in the mean time. I did run into another issue though, because of the way you are calling the touchedX function in your code in the touchesBegan and touchesMoved, it is firing the sectionChanged function excessively, which is not ideal and can lead to issues. I ran into similar issues when trying to implement pan gestures, but was able to use the state of the gesture to fix the issue. The same fix may be worth trying here too. I'm not sure if you noticed this, but calling this so frequently will tie up the main thread and cause UI elements to respond slowly too.

**Comment by sdevo619** [comment]
Thank for looking into this. Also, just FYI I did try to install it again using the CocoaPod route after deleting derived data and i am still seeing this error.

[!] Unable to find a specification for `SectionedSlider (~> 0.0.2)`

Any ideas?

Regarding the other issue, I added a print statement to the sectionChanged code with a counter variable and it is firing between 150-350 times depending on how quickly i drag up and down. This is what I mean by excessive.

**Comment by leonardocardoso** [comment]
It seems your have a misconfiguration on your CocoaPods. You can find it here https://cocoapods.org/?q=SectionedSlider.

**Comment by sdevo619** [comment]
I disagree with you on that. I have multiple other pods in this same project which work fine, and will complete a pod install when yours is commented out. BTW you also have different build numbering listed on git hub and the cocoa pods website. As I said, I already have it working by adding it manually, so it's not a huge deal, but it doesn't work as a pod. Any luck with a fix for the other issue I reported about the sectionChanged function?
GitHub:
pod 'SectionedSlider', '~> 0.0.2'

CocoaPods:
  pod 'SectionedSlider', '~> 0.0'

I don't see why the minimum build number difference should matter, but neither of these work unfortunately.

**Comment by leonardocardoso** [comment]
Can you try `pod 'SectionedSlider', '0.0.2'`? Regarding the touches, the code is indeed watching every touch and "drag" for a better visualisation, maybe I will change that in the future as long as it does not interfere with the look and feel. If you are debugging using print statements, you need to be aware that this slows down the performance of the app.

**Comment by sdevo619** [comment]
That unfortunately didn't fix the pod issue. Here is the new error.
[!] Unable to find a specification for `SectionedSlider (= 0.0.2)`

I understand what you mean about the print statement, but that is not the issue. Lets take for example Apple's Home Kit. Say I am using SectionSlider to adjust dimming of the lights. HomeKit does not like having the function to adjust the brightness on the lights fired 300 times in a row this quickly, and the same goes for using this to adjust volume. Unless you can come up with a solution to this, it will more than likely cause issues is most of the cases you would want to use it. 

Also, as another recommendation, it would be nice to be able to set the initial section slider value in code without firing the sectionChanged function. There may be a way to do this now, but I haven't been able to figure it out. 

Another issue is, that because you can only adjust things in 5% increments instead of 1% increments due to the 20 section limit, it will further limit the use cases. Any possibility of bumping up the section limit to 100?
