### ISSUE TITLE
selectedSection is inaccessible due to internal protection level

### ISSUE THREAD

**Issue by JonnyLinja** [LeonardoCardoso/SectionedSlider#7]
I have the slider in a tableviewcell and need to set the selectedSection each time cellForRowAtIndexPath is called. The property however is not accessible.

**Comment by leonardocardoso** [comment]
For now you can implement the protocol to get updates whenever it changes and save it to a variable or even map it on an array.

```swift
public protocol SectionedSliderDelegate {
   
	func sectionChanged(slider: SectionedSlider, selected: Int)
   
}
```

**Comment by JonnyLinja** [comment]
Submitted PR #9
