### ISSUE TITLE
Cannot scroll when embedded in a scrollView

### ISSUE THREAD

**Issue by JonnyLinja** [LeonardoCardoso/SectionedSlider#8]
I've placed the SectionedSlider in a UITableViewCell and cannot scroll it. The tableview scrolls whenever I try.

**Comment by leonardocardoso** [comment]
This view is not meant for that. But this must be related to dragging delegates of the UITableView or UITableViewCell, or even with the flag `isUserInteractionEnabled` on the cell. Maybe you could try to manipulate them and check whether it works or not. Then go back here to comment.

**Comment by JonnyLinja** [comment]
Submitted PR #9
